import { Router } from "express";
import PDFDocument from "pdfkit";
import { Lease } from "../models/Lease";
import { RentPayment } from "../models/RentPayment";
import { User } from "../models/User";
import mongoose from "mongoose";
import { authenticate } from "../middleware/authenticate";
import { asyncHandler } from "../utils/asyncHandler";
import { httpError } from "../middleware/errorHandler";
import { requireObjectId } from "../utils/objectId";
import { assertLeaseInStaffScope } from "../services/propertyAccess";

export const rentPaymentReceiptRouter = Router();

rentPaymentReceiptRouter.get(
  "/:paymentId/receipt",
  authenticate,
  asyncHandler(async (req, res) => {
    const auth = req.auth!;
    const paymentId = requireObjectId(req.params.paymentId, "paymentId");

    const payment = await RentPayment.findById(paymentId).lean();
    if (!payment || Array.isArray(payment)) {
      throw httpError(404, "Payment not found", "NOT_FOUND");
    }

    const p = payment as Record<string, unknown>;
    const orgIdStr = String(p.organizationId);

    if (auth.organizationId !== orgIdStr) {
      throw httpError(403, "Forbidden", "FORBIDDEN");
    }

    const lease = await Lease.findOne({
      _id: p.leaseId,
      organizationId: p.organizationId,
    }).lean();

    if (!lease || Array.isArray(lease)) {
      throw httpError(404, "Lease not found", "NOT_FOUND");
    }

    const l = lease as Record<string, unknown>;
    if (auth.role === "tenant") {
      if (String(l.tenantUserId) !== auth.userId) {
        throw httpError(403, "Forbidden", "FORBIDDEN");
      }
    } else if (auth.role === "landlord" || auth.role === "agent") {
      await assertLeaseInStaffScope(
        new mongoose.Types.ObjectId(auth.organizationId),
        { unitId: l.unitId as mongoose.Types.ObjectId },
        auth
      );
    } else {
      throw httpError(403, "Forbidden", "FORBIDDEN");
    }

    const tenant = await User.findById(l.tenantUserId).lean();
    const tenantEmail =
      tenant && !Array.isArray(tenant)
        ? String((tenant as { email?: string }).email ?? "")
        : "";

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="tenantos-receipt-${paymentId}.pdf"`
    );

    const doc = new PDFDocument({ margin: 50 });
    doc.pipe(res);

    doc.fontSize(18).text("TenantOS", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(14).text("Rent payment receipt", { align: "center" });
    doc.moveDown(1.5);

    doc.fontSize(11);
    doc.text(`Receipt ID: ${String(p._id)}`);
    doc.text(`Paid at: ${new Date(p.paidAt as Date).toISOString()}`);
    doc.text(`Amount: ${Number(p.amount).toFixed(2)} ${String(p.currency)}`);
    doc.text(`Method: ${String(p.method)}`);
    if (p.paystackReference) {
      doc.text(`Reference: ${String(p.paystackReference)}`);
    }
    doc.moveDown();
    doc.text(`Lease ID: ${String(l._id)}`);
    if (tenantEmail) {
      doc.text(`Tenant: ${tenantEmail}`);
    }
    doc.moveDown(2);
    doc.fontSize(9).fillColor("#666").text("Generated by TenantOS", { align: "center" });

    doc.end();
  })
);
